### PR TITLE
Tickets #70, #73, #74, #75 for the search box

### PR DESCRIPTION
**Pull request by Hedro95**
This PR is for the quiz search box functionality. I was able have the code connect to this database. This was in order to get the list of quiz names which would then be parsed through to see all of the relevant ones according to the keyword typed in the search box. Once the list was gotten, it would show the titles of the top three searches.

### CODE REVIEW

**Comment by sudthebud** [comment]
Exciting to see the functionality you've implemented. It's nice that you created a "change scene" script to make it simpler for us to change scenes. Looking forward to using the search feature; it's nice to see our application coming together after these first few months.

**Comment by tguadiano** [comment]
Search code looks good, this will come in hand when sorting through the api calls

**Comment by tguadiano** [comment]
Good to see that the search functionality is looking clean and readable. This is a very crucial aspect of expectations that user will utilize

**Comment by kylemfry3** [comment]
These changes have been saved and moved over to branch stable_sprint3.

**Pull request closed without merging**
