### PR TITLE
Implemented Game

### PR DESCRIPTION
**Pull request by sudthebud**
Implemented backend of game, made changes to frontend to accommodate game, fixed some other bugs related to frontend. Took way too long.

### CODE REVIEW

**Comment by tguadiano** [comment]
looks good to me there seems to be a conflict with main that stopping the merge

**Comment by sudthebud** [comment]
By the way, this has all of the frontend stuff for the game plus some fixes/additions of my own, so either merge Adeja's changes in before merging these changes, or don't merge Adeja's changes in at all.

**Comment by sudthebud** [comment]
Actually, I closed her PR anyway, so just use this PR to merge all the game stuff in.

**Review by adejamann — COMMENTED** [review]
The game looks good and works great. Thanks for all your hard work!

**Pull request merged**
