### PR TITLE
Game update

### PR DESCRIPTION
**Pull request by adejamann**
All the game screens

### CODE REVIEW

**Comment by tguadiano** [comment]
Game screensw look really good!

**Comment by msunglim** [comment]
Nice work! Beautiful scene :)

**Comment by Hedro95** [comment]
The screens look great! However, the user history screen seems to be throwing an error about a it not having a string assigned.

**Comment by sudthebud** [comment]
Solid and function UI, with added flair. Very impressive.

**Comment by sudthebud** [comment]
Redundant now that these changes have been merged into backend implementation and a new PR was created. Closing this PR.

**Pull request closed without merging**
